const pptxgen = require('pptxgenjs');
const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'Stranger Strings';
pptx.subject = 'SIH 2026 Problem Statement 26188';
pptx.title = 'SENTINEL-ID — AI based Fake Identity and Document Screening System';
pptx.company = 'Stranger Strings';
pptx.lang = 'en-IN';
pptx.theme = { headFontFace: 'Arial', bodyFontFace: 'Arial', lang: 'en-US' };
pptx.defineSlideMaster({ title:'SIH', background:{ color:'E7ECF0' }, objects:[
  { line:{ x:0.64,y:7.05,w:12.05,h:0,line:{color:'C0CAD3',width:1} } },
  { text:{ text:'SMART INDIA HACKATHON 2026  /  SOFTWARE  /  CYBERSECURITY', options:{x:0.66,y:7.12,w:7.2,h:0.18,fontFace:'Arial',fontSize:7.5,bold:true,color:'46586A',charSpacing:1.2,margin:0} } },
  { text:{ text:'STRANGER STRINGS', options:{x:10.45,y:7.12,w:2.2,h:0.18,fontFace:'Arial',fontSize:7.5,bold:true,color:'46586A',align:'right',margin:0} } },
]});
const C={ink:'131C24',slate:'46586A',rule:'C0CAD3',booth:'E7ECF0',sunk:'DAE1E7',paper:'FFFFFF',green:'06603F',amber:'9A5300',red:'8E1414',cyan:'00A3C4',mag:'C026D3',lightGreen:'E6F0EB',lightAmber:'F5EBDF',lightBlue:'E4E8EC'};
const W=13.333,H=7.5;
function tx(s,text,x,y,w,h,size=14,opt={}){s.addText(text,{x,y,w,h,fontFace:opt.fontFace||'Arial',fontSize:size,color:opt.color||C.ink,bold:!!opt.bold,italic:!!opt.italic,breakLine:false,fit:'shrink',margin:opt.margin??0,align:opt.align||'left',valign:opt.valign||'mid',bullet:opt.bullet,paraSpaceAfterPt:opt.paraSpaceAfterPt||0,charSpacing:opt.charSpacing||0});}
function rect(s,x,y,w,h,fill=C.paper,line=C.rule,r=0){s.addShape(pptx.ShapeType.rect,{x,y,w,h,rectRadius:r,fill:{color:fill},line:{color:line,width:1}});}
function line(s,x,y,w,h,color=C.rule,width=1,dash='solid'){s.addShape(pptx.ShapeType.line,{x,y,w,h,line:{color,width,dashType:dash,beginArrowType:'none',endArrowType:'none'}});}
function section(s,kicker,title,sub){tx(s,kicker.toUpperCase(),0.68,0.36,5.6,0.2,8,{bold:true,color:C.slate,charSpacing:1.4});tx(s,title,0.66,0.66,11.9,0.48,25,{bold:true});if(sub)tx(s,sub,0.68,1.18,11.7,0.28,10,{color:C.slate});}
function tag(s,t,x,y,w,fill=C.sunk,color=C.ink){rect(s,x,y,w,0.28,fill,fill);tx(s,t,x+0.08,y+0.02,w-0.16,0.22,8,{bold:true,color,charSpacing:0.5});}
function card(s,x,y,w,h,title,body,accent=C.ink){rect(s,x,y,w,h,C.paper,C.rule);s.addShape(pptx.ShapeType.rect,{x,y,w:0.06,h,fill:{color:accent},line:{color:accent}});tx(s,title,x+0.2,y+0.18,w-0.35,0.26,12,{bold:true});tx(s,body,x+0.2,y+0.55,w-0.38,h-0.68,10,{color:C.slate,valign:'top'});}
function dot(s,x,y,color){s.addShape(pptx.ShapeType.ellipse,{x,y,w:0.14,h:0.14,fill:{color},line:{color}});}
function footerNo(){ }

// 1
{const s=pptx.addSlide('SIH');section(s,'SIH 2026 / Problem Statement 26188','AI based Fake Identity and Document Screening System','An explainable, on-premise screening platform for faster and safer border verification.');
rect(s,0.68,1.78,7.65,4.55,C.paper,C.rule);tx(s,'SENTINEL-ID',1.0,2.22,6.6,0.42,30,{bold:true,color:C.ink,charSpacing:1.5});tx(s,'The document is the evidence.\nThe machine is the annotator.',1.0,2.95,5.8,0.85,22,{bold:true});line(s,1.0,4.1,5.9,0,C.rule,1);tx(s,'MRZ-first validation  ·  forensic tamper signals  ·  face verification  ·  calibrated risk',1.0,4.35,6.5,0.46,12,{color:C.slate});tag(s,'BLOCKCHAIN & CYBERSECURITY',1.0,5.2,2.55,C.lightBlue,C.ink);tag(s,'SOFTWARE',3.75,5.2,1.05,C.lightBlue,C.ink);
rect(s,8.7,1.78,3.95,4.55,C.sunk,C.rule);tx(s,'OFFICIAL METADATA',9.02,2.1,3.2,0.25,9,{bold:true,color:C.slate,charSpacing:1.3});const rows=[['Problem Statement ID','26188'],['Theme','Blockchain & Cybersecurity'],['PS Category','Software'],['Team ID',''],['Team Name','Stranger Strings']];rows.forEach((r,i)=>{const y=2.62+i*0.62;tx(s,r[0].toUpperCase(),9.02,y,1.55,0.2,8,{bold:true,color:C.slate,charSpacing:0.7});if(i===3){rect(s,10.62,y-0.03,1.55,0.27,C.paper,C.rule)}else tx(s,r[1],10.62,y,1.75,0.23,10,{bold:true});if(i<rows.length-1)line(s,9.02,y+0.42,3.18,0,C.rule)});tx(s,'‹‹‹  OFFICER-LED DECISION SUPPORT  ‹‹‹',8.98,5.95,3.2,0.2,8,{bold:true,color:C.slate,charSpacing:0.8});}

// 2
{const s=pptx.addSlide('SIH');section(s,'02 / Idea Title','From document image to defensible decision','A focused pipeline that turns hidden fraud signals into evidence an officer can act on.');
rect(s,0.68,1.78,4.0,4.85,C.sunk,C.rule);tx(s,'THE PROBLEM',1.0,2.08,2.4,0.25,9,{bold:true,color:C.red,charSpacing:1.3});tx(s,'Fake identities hide in plain sight.',1.0,2.46,3.0,0.5,20,{bold:true});tx(s,'A thirty-second manual glance can miss:',1.0,3.2,3.2,0.25,11,{color:C.slate});['Replaced portraits and face morphs','Retyped dates or document numbers','Copy-moved stamps and recompressed regions','The same traveller under multiple names'].forEach((t,i)=>{dot(s,1.02,3.72+i*0.48,C.red);tx(s,t,1.28,3.65+i*0.48,3.0,0.28,10,{color:C.ink});});tx(s,'The cost is not only delay — it is inconsistent decisions and weak evidence trails.',1.0,5.75,3.1,0.5,10,{color:C.slate,italic:true});
line(s,4.98,2.1,0,4.25,C.rule,2);tx(s,'THE SOLUTION',5.42,2.08,2.4,0.25,9,{bold:true,color:C.green,charSpacing:1.3});tx(s,'SENTINEL-ID',5.42,2.46,3.3,0.46,22,{bold:true});tx(s,'A calibrated, offline-first screening console that keeps the officer in control.',5.42,3.0,6.8,0.35,12,{color:C.slate});
[['01','MRZ-FIRST','Deterministic check digits before model inference.'],['02','FORENSICS','12 interpretable signals with visual evidence.'],['03','FACE + GALLERY','Match, morph, liveness, and alias detection.'],['04','EXPLAINABLE RISK','Refer or hold only with a human-readable reason.']].forEach((r,i)=>{const x=5.42+(i%2)*3.35,y=3.72+Math.floor(i/2)*1.23;card(s,x,y,3.05,0.95,r[1],r[2],i===3?C.green:C.cyan);tx(s,r[0],x+2.48,y+0.17,0.38,0.2,9,{bold:true,color:C.slate,align:'right'});});}

// 3
{const s=pptx.addSlide('SIH');section(s,'03 / Technical Approach','A staged architecture built for explainability','Capture quality gates expensive inference; every downstream signal contributes evidence, not an opaque verdict.');
const blocks=[['CAPTURE','Scanner / camera / NFC'],['QUALITY GATE','Glare · blur · DPI'],['OCR + MRZ','Fields · 7-3-1 checks'],['VALIDATION','Rules · watchlist · reuse'],['FORENSICS','JPEG · PRNU · font · stamp'],['FACE','Match · PAD · morph · gallery'],['RISK FUSION','Calibrate · explain · audit']];
blocks.forEach((b,i)=>{const x=0.75+i*1.78,y=2.15;rect(s,x,y,1.46,0.9,i===6?C.lightGreen:C.paper,i===6?C.green:C.rule);tx(s,b[0],x+0.1,y+0.17,1.25,0.2,9,{bold:true,align:'center'});tx(s,b[1],x+0.1,y+0.47,1.25,0.28,7,{color:C.slate,align:'center'});if(i<blocks.length-1){line(s,x+1.47,y+0.45,0.31,0,C.slate,1.5);s.addShape(pptx.ShapeType.chevron,{x:x+1.67,y:y+0.37,w:0.12,h:0.16,fill:{color:C.slate},line:{color:C.slate}})}});
line(s,2.24,3.18,8.32,0,C.rule,1);tx(s,'EVIDENCE LOOP',0.76,3.35,1.7,0.2,8,{bold:true,color:C.slate,charSpacing:1.1});[['document crops','field confidence'],['heatmaps','human-readable reasons'],['hash chain','officer override']].forEach((b,i)=>{const x=2.55+i*3.0;rect(s,x,3.25,2.6,0.5,C.sunk,C.sunk);tx(s,b[0].toUpperCase(),x+0.12,3.35,2.35,0.16,8,{bold:true});tx(s,b[1],x+0.12,3.55,2.35,0.12,7,{color:C.slate});});
tx(s,'STACK',0.75,4.32,1.0,0.2,9,{bold:true,color:C.slate,charSpacing:1.3});const stack=[['UI','Next.js · React · TypeScript'],['API','FastAPI · Pydantic · REST / SSE'],['AI','OpenCV · Tesseract · ONNX Runtime'],['DATA','PostgreSQL · pgvector · MinIO'],['SECURITY','Docker · offline bundles · hash-chained audit']];stack.forEach((r,i)=>{const x=0.75+(i%3)*4.05,y=4.68+Math.floor(i/3)*0.72;rect(s,x,y,3.65,0.52,C.paper,C.rule);tx(s,r[0],x+0.14,y+0.11,0.72,0.18,8,{bold:true,color:C.cyan});tx(s,r[1],x+0.94,y+0.09,2.5,0.24,10,{bold:true});});}

// 4
{const s=pptx.addSlide('SIH');section(s,'04 / Feasibility & Viability','Practical at the checkpoint. Scalable across the network.','The MVP is deliberately bounded: offline-ready, modular, and measurable against a real latency and accuracy budget.');
card(s,0.75,1.9,5.75,4.52,'TECHNICAL FEASIBILITY','• On-premise pipeline keeps sensitive images inside the checkpoint.\n\n• p95 screening target ≤ 4 seconds on reference hardware.\n\n• CPU fallback and declared capture profiles keep the system usable when GPU or NFC is unavailable.\n\n• Modular signals can be shipped, tested, and calibrated independently.\n\n• Deterministic MRZ rules create an explainable baseline before AI inference.',C.cyan);
card(s,6.83,1.9,5.75,4.52,'COMMERCIAL VIABILITY','• Reduces manual review time and standardises screening quality.\n\n• Reuses existing scanners and officer workflow; no traveller-facing app required.\n\n• Expandable from passports to visas, IDs, permits, and eKYC evidence.\n\n• Audit trail supports investigations, supervisor overrides, and compliance.\n\n• Deployment model fits border checkpoints, airports, and high-assurance facilities.',C.green);
tag(s,'MVP → PILOT → NETWORK SCALE',4.28,6.72,4.7,C.ink,C.paper);}

// 5
{const s=pptx.addSlide('SIH');section(s,'05 / Impact & Benefits','Faster screening without lowering the bar','Benefits are measured where trust matters: time, consistency, evidence, and safer decisions.');
const benefits=[['01','OFFICERS','One glanceable verdict with a specific reason — less cognitive load under queue pressure.',C.cyan],['02','TRAVELLERS','Fewer unnecessary referrals because uncertainty is separated from suspicion.',C.green],['03','SUPERVISORS','Evidence overlays, field crops, and override reasons make escalations reviewable.',C.amber],['04','INVESTIGATORS','Searchable, tamper-evident records expose repeat identities and shared forgery patterns.',C.mag],['05','SYSTEM OWNERS','Offline operation, signed watchlist bundles, and versioned rules protect sovereignty.',C.ink]];
benefits.forEach((b,i)=>{const x=0.76+i*2.48;rect(s,x,2.0,2.22,3.95,C.paper,C.rule);s.addShape(pptx.ShapeType.ellipse,{x:x+0.18,y:2.25,w:0.58,h:0.58,fill:{color:b[3]},line:{color:b[3]}});tx(s,b[0],x+0.18,2.39,0.58,0.18,9,{bold:true,color:C.paper,align:'center'});tx(s,b[1],x+0.18,3.05,1.8,0.24,11,{bold:true});tx(s,b[2],x+0.18,3.52,1.82,1.42,10,{color:C.slate,valign:'top'});line(s,x+0.18,5.3,1.82,0,b[3],2);});tx(s,'TARGET OUTCOMES',0.78,6.34,1.7,0.2,8,{bold:true,color:C.slate,charSpacing:1.2});tx(s,'≤ 4s p95 screening  ·  ≥ 0.92 AUC  ·  100% explained non-CLEAR verdicts  ·  100% hash-chained audit records',2.5,6.31,9.5,0.28,10,{bold:true});}

// 6
{const s=pptx.addSlide('SIH');section(s,'06 / Research & References','Evidence-led by design','The proposal is grounded in public standards, established computer-vision tooling, and current forgery-detection research.');
rect(s,0.75,1.82,5.55,4.88,C.paper,C.rule);rect(s,6.55,1.82,6.03,4.88,C.paper,C.rule);tx(s,'RESEARCH',1.02,2.12,2.1,0.25,10,{bold:true,color:C.green,charSpacing:1.3});const research=['Studied existing OCR & document verification methods','Reviewed passport/ID security & common document tampering techniques','Explored face matching for identity verification','Tools / AI-assisted study: ChatGPT, OpenCV, Tesseract OCR, Claude'];research.forEach((t,i)=>{dot(s,1.05,2.72+i*0.67,C.green);tx(s,t,1.35,2.62+i*0.67,4.45,0.38,10,{color:C.ink,valign:'top'});if(i<3)line(s,1.02,3.23+i*0.67,4.8,0,C.rule)});
tx(s,'REFERENCES',6.85,2.12,2.1,0.25,10,{bold:true,color:C.cyan,charSpacing:1.3});const refs=['NIST – Digital Identity Guidelines (SP 800-63A)','ICAO – Machine Readable Travel Documents (MRTD)','Tesseract OCR – Official Documentation','OpenCV – Official Documentation','NIST – Considerations for Implementing Morph Detection in Operations','NIST Face Recognition Vendor Test (FRVT)','ICAO Doc 9303 – Machine Readable Travel Documents','“Towards Robust Tampered Text Detection in Document Image: New Dataset and New Solution” – Chenfan Qu et al., IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2023','“Document forgery detection: a comprehensive review” – Sukhija, Kumar & Jindal, International Journal of Data Science and Analytics, 2025','“Document Images Forgery Localization Using a Two-Stream Network” – Xu et al., 2022'];refs.forEach((t,i)=>{const y=2.56+i*0.38;tx(s,`${i+1}.`,6.86,y,0.24,0.22,7,{bold:true,color:C.cyan});tx(s,t,7.15,y,5.0,0.31,7.1,{color:C.ink,valign:'top'});});tx(s,'‹‹‹  STANDARDS → SIGNALS → SCREENING  ‹‹‹',0.78,6.86,5.5,0.18,8,{bold:true,color:C.slate,charSpacing:0.9});}

pptx.writeFile({ fileName:'/vercel/share/v0-project/public/SENTINEL-ID_SIH2026_Final_6_Slides.pptx' });
console.log('[v0] Generated SIH 2026 deck');
